name: publish

on: [push]

jobs:
  publish-nomad-letsencrypt-sidecar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the nomad-letsencrypt-sidecar Docker image
      run: |
        echo $CONTAINER_REGISTRY_TOKEN | docker login ghcr.io -u t0k4rt --password-stdin
      env:
        CONTAINER_REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}